### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by benedekrozemberczki** [gbrltv/business_process_encoding#2]
Can you cite the Karate Club paper in the final work that is submitted?

@inproceedings{karateclub,
       title = {{Karate Club: An API Oriented Open-source Python Framework for Unsupervised Learning on Graphs}},
       author = {Benedek Rozemberczki and Oliver Kiss and Rik Sarkar},
       year = {2020},
       pages = {3125–3132},
       booktitle = {Proceedings of the 29th ACM International Conference on Information and Knowledge Management (CIKM '20)},
       organization = {ACM},
}

**Comment by gbrltv** [comment]
Yes, we'll definitely do that! Thank you.
